source :gemcutter

gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'arel', :git => 'git://github.com/rails/arel.git'
gem 'rack', :git => 'git://github.com/rails/rack.git'

gem 'inherited_resources'
gem 'hpricot'

group :db do
  gem 'pg'
end

group :webserver do
  gem 'unicorn'
end

# Deploy with Capistrano
# gem 'capistrano'

# Bundle the extra gems:
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

group :test do
  gem 'rspec', '>= 2.0.0.beta.1'
  gem 'rspec-rails', '>= 2.0.0.beta.1'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'cucumber-rails'
end
